-- 1. Table: game_balance_questions (질문 데이터)
CREATE TABLE IF NOT EXISTS public.game_balance_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    question_a TEXT NOT NULL,
    question_b TEXT NOT NULL,
    desc_a TEXT,  -- A 선택 시 나올 멘트
    desc_b TEXT,  -- B 선택 시 나올 멘트
    count_a BIGINT DEFAULT 0,
    count_b BIGINT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    total_votes BIGINT GENERATED ALWAYS AS (count_a + count_b) STORED
);

-- 2. Table: game_balance_rankings (랭킹 데이터)
CREATE TABLE IF NOT EXISTS public.game_balance_rankings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nickname TEXT NOT NULL,
    score INTEGER NOT NULL, -- 성향 점수 (예: 0~100)
    title TEXT,             -- 칭호 (예: '현실주의자', '낭만파')
    mbti_result TEXT        -- 선택 내용 기반 추정 성향
);

-- 3. RPC: Vote Function (Atomic Increment)
CREATE OR REPLACE FUNCTION vote_balance_game(question_id BIGINT, choice TEXT)
RETURNS VOID AS $$
BEGIN
  IF choice = 'A' THEN
    UPDATE public.game_balance_questions
    SET count_a = count_a + 1
    WHERE id = question_id;
  ELSIF choice = 'B' THEN
    UPDATE public.game_balance_questions
    SET count_b = count_b + 1
    WHERE id = question_id;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- 4. RPC: Submit Score (랭킹 등록)
CREATE OR REPLACE FUNCTION submit_balance_score(p_nickname TEXT, p_score INTEGER, p_title TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO public.game_balance_rankings (nickname, score, title)
  VALUES (p_nickname, p_score, p_title);
END;
$$ LANGUAGE plpgsql;

-- 5. RLS Setup (Optional but recommended)
ALTER TABLE public.game_balance_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_balance_rankings ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Enable read access for all users" ON public.game_balance_questions FOR SELECT USING (true);
CREATE POLICY "Enable read access for rankings" ON public.game_balance_rankings FOR SELECT USING (true);

-- Allow insert access via RPC (Direct insert might be blocked depending on config, but RPC bypasses RLS usually)
-- For public insert (if not using RPC for rankings):
CREATE POLICY "Enable insert for rankings" ON public.game_balance_rankings FOR INSERT WITH CHECK (true);

-- 6. Sample Data (100 Questions) - 일부 예시, 나머지는 별도 실행
INSERT INTO public.game_balance_questions (question_a, question_b, desc_a, desc_b) VALUES
('월 200 백수 (평생 노가다 X)', '월 600 직장인 (주 6일 야근)', '당신은 자유로운 영혼! 돈보다 시간이 중요하군요.', '금융치료가 최고죠! 통장 잔고가 곧 행복입니다.'),
('다시 태어난다면? (외모 하위 1% 재벌 2세)', '다시 태어난다면? (외모 상위 1% 빚 10억)', '돈으로 모든 걸 해결하는 플렉스 인생!', '얼굴이 복지다! 빚은 갚으면 그만이죠.'),
('1년 동안 스마트폰 없이 살기 (10억 지급)', '평생 스마트폰 쓰기 (보상 없음)', '디지털 디톡스 성공! 10억이면 참을 만하죠.', '스마트폰 없는 세상은 상상조차 할 수 없어요.'),
('절친과 전애인이 사귀기', '전애인과 절친이 사귀기 (내 전애인이 절친과)', '차라리 모르는 게 약... 쿨하게 보내줍니다.', '내 친구랑 내 전애인이라니... 절대 용납 불가!'),
('평생 라면만 먹기', '평생 탄산음료 안 마시기', '라면은 소울푸드죠! 탄산 따위 참을 수 있습니다.', '콜라 없는 인생은 상상 불가! 차라리 밥을 먹겠어요.'),
('나만 바라보는 못생긴 애인', '바람기 다분한 존잘/존예 애인', '얼굴 뜯어먹고 살 거 아니니까... 마음이 중요해!', '얼굴값 하는 건 용서 가능! 예쁜 게 최고야.'),
('화장실 갈 때마다 휴지 없음', '밥 먹을 때마다 젓가락 한 짝 없음', '휴지 없는 공포... 손으로 해결할 순 없잖아요?', '손으로 먹는 게 낫죠. 휴지 없는 건 생존 문제입니다.'),
('100% 확률로 1억 받기', '50% 확률로 100억 받기', '안전제일! 확실한 1억이 최고입니다.', '인생은 한방! 100억에 승부를 겁니다.'),
('남들이 내 속마음 다 듣기', '남들이 내 알몸 다 보기', '속마음 들키면 사회생활 불가... 차라리 몸을 보여줄래.', '몸은 가릴 수 있지만 생각은 못 막잖아요. 속마음 사수!'),
('평생 여름 (에어컨 없음)', '평생 겨울 (난방 없음/패딩 가능)', '더위는 못 참아! 껴입으면 되는 겨울이 낫습니다.', '추위는 뼈가 시려요... 차라리 땀 흘리는 여름이 낫죠.'),
('친구 100명 (진정한 친구 0명)', '친구 1명 (내 목숨 구해줄 친구)', '인맥이 곧 능력! 넓고 얕은 관계가 도움됩니다.', '진정한 한 사람이면 충분해. 양보다 질이죠.'),
('토요일마다 회사 등산 (사장님과 단둘이)', '일요일마다 조기축구 (부장님과 풀타임)', '차라리 등산이 낫죠... 축구는 몸이 부서집니다.', '등산은 고문이야... 공 차고 땀 흘리는 게 낫습니다.');
